#cloud-config

coreos:
  etcd:
    discovery: ${token}
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4
    metadata: region=AMS3
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: iptables-restore.service
      enable: true

# write_files:
#   - path: /var/lib/iptables/rules-save
#     permissions: 0644
#     owner: root:root
#     content: |
#       *filter
#       :INPUT DROP [0:0]
#       :FORWARD DROP [0:0]
#       :OUTPUT ACCEPT [0:0]
#       -A INPUT -i lo -j ACCEPT
#       -A INPUT -i eth1 -j ACCEPT
#       -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
#       -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
#       -A INPUT -p tcp -s $private_ipv4/32 --dport 4001 -j ACCEPT
#       -A INPUT -p tcp -s $private_ipv4/32 --dport 7001 -j ACCEPT
#       -A INPUT -p icmp -j ACCEPT
#       -A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7
#       COMMIT
